apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-sample-app1
spec:
  template:
    spec:
      containers:
        - name: argo-sample
          resources:
            limits:
              cpu: 250m
              memory: 256Mi   