apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-sample-app1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: argo-sample-app1
  template:
    metadata:
      labels:
        app: argo-sample-app1
    spec:
      containers:
        - name: argo-sample
          image: overlay-sample-image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi           
