apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-app4
  namespace: fluxcd
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: fluxcd-sync
  path: './fluxcd/flux-apps/app4/overlays/prod/'
  prune: true
  targetNamespace: flux-apps