apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-sample-app3
spec:
  template:
    spec:
      containers:
        - name: flux-sample
          resources:
            limits:
              cpu: 250m
              memory: 256Mi   