apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-sample-app3-prod
  namespace: flux-system
resources:
- ../../base
patchesStrategicMerge:
- deployment-limits.yaml
images:
- name: overlay-sample-image
  newName: mcr.microsoft.com/dotnet/samples
  newTag: aspnetapp