apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-sample-app4
spec:
  template:
    spec:
      containers:
        - name: flux-sample
          resources:
            limits:
              cpu: 500m
              memory: 512Mi   